on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: "build.yaml"
      config_path: "config"
      fallback_binary: true
      cmake_args: "-DCONFIG_ZMK_BOARD_COMPAT=y"
